---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "default"
  name: pgpool-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pgpool-operator-cluster-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "default"
  name: pgpool-operator-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pgpool-operator-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pgpool-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: pgpool-operator
    namespace: "default"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "default"
  name: pgpool-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pgpool-operator-role
subjects:
  - kind: ServiceAccount
    namespace: "default"
    name: pgpool-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pgpool-operator
  template:
    metadata:
      labels:
        app: pgpool-operator
    spec:
      serviceAccountName: pgpool-operator
      containers:
        - name: operator
          image: python:3.10-bullseye
          command: ["/bin/sh", "-c", "pip3 install kopf kubernetes && kopf run /app/pgpool.py --standalone --namespace=default --log-format=plain --liveness=http://0.0.0.0:8080/healthz"]
          volumeMounts:
            - name: pgpool-operator-script
              mountPath: /app
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 1Gi
      volumes:
        - name: pgpool-operator-script
          configMap:
            name: pgpool-operator-script
